#!/bin/bash

declare -a tests=("test-simple-success" "test-simple-fail")
cd "$(dirname "$0")"

exec_test() {
    mkdir env/
    cp $1/* env/
    cp -r ../student/CTester env/
    cp ../student/Makefile env/
    pushd env

    make
    echo "### $1: executing ..."
    ./tests

    if [ -f ./results.txt ]; then
        cmp --silent results.txt expected_results.txt
        if [ $? -eq 0 ]; then
            echo '###' $1 ': OK'
            pushd
            rm -rf env
            return 1
        else
            echo '###' $1 ': results.txt diverges from the expected output:'
            diff results.txt expected_results.txt
        fi
    else
        echo '###' $1 ': CTester did not create a results.txt file'
    fi

    popd
    rm -rf env
    return 0
}


echo '### Executing tests'
tests_ok=0

for i in "${tests[@]}"
do
    echo '##########' $i
    exec_test $i
    if [ $? -eq '1' ]; then
        tests_ok=$((tests_ok+1))
    fi

done

echo '###' $tests_ok '/' ${#tests[@]} 'tests succeeded'
if ((tests_ok != ${#tests[@]})); then
    exit 1
else
    exit 0
fi
